name: Node.js CI

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/nodejs-ci.yml'
      - 'apps/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Enable yarn by corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format check (Prettier)
        run: yarn format:check

      - name: CSS Lint (stylelint)
        run: yarn lint:css

      - name: Spellcheck (cspell)
        run: yarn spellcheck

      - name: Build (all workspaces)
        run: yarn build

      - name: Test (Vitest)
        run: yarn test

      - name: Typecheck (all workspaces)
        run: yarn typecheck

      - name: Lint admin
        run: yarn workspace @bplus/admin lint

      - name: Lint participant
        run: yarn workspace @bplus/participant lint
